var ACTIVE_EXPRESIONES_CONDICIONALES = false,
    ACTIVE_ALCANCE_FUNCIONES = false,
    ACTIVE_INHERITANCE_PSEUDOCLASSICAL = false,
    ACTIVE_INHERITANCE_PROTOTYPAL = false,
    ACTIVE_INHERITANCE_FUNCTIONAL = true;

if (!(ACTIVE_EXPRESIONES_CONDICIONALES ||
   ACTIVE_ALCANCE_FUNCIONES ||
   ACTIVE_INHERITANCE_PSEUDOCLASSICAL ||
   ACTIVE_INHERITANCE_PROTOTYPAL ||
   ACTIVE_INHERITANCE_FUNCTIONAL)) {
  console.log('Activar algun ejemplo desde "terminal.js"');
}
    